### ISSUE TITLE
Replace JS with TypeScript

### ISSUE THREAD

**Issue by dakur** [grifart/simple-webpack#7]
Even that configuration file itself is written in TypeScript, current set up does not support TypeScript in projects.

I suggest to remove support for .js files completely and add support for .ts.

**Comment by jkuchar** [comment]
I have plan to support TypeScript & JavaScript for the best interopability and zero setup.

**Comment by jkuchar** [comment]
Work in progress implementation: https://github.com/grifart/simple-webpack/pull/10

**Comment by jkuchar** [comment]
implemented in #10
